name: MSc-Math-Finance-Projects-env

channels:
  - QuantStack
  - conda-forge

dependencies:
  - xeus-cling=0.15.0
#  - gcc_linux-64=9.3.0
  - notebook=6.5.2
  - boost-cpp=1.72.0
  - requests
  - pandas
  - xmltodict
