name: MSc-Math-Finance-Projects-env

channels:
  - QuantStack
  - conda-forge

dependencies:
  - xeus-cling=0.13
  - notebook
  - boost=1.72.0
  - gcc_linux-64=9.3.0
  - requests
  - pandas
  - xmltodict
